# Project
author      : Zach Williams, @zachwill
analytics   : UA-XXXXX-X
description : "Macon MTA will be sponsoring a Try Transit week June 24-28."
title       : Try MTA Transit

# Defaults
pygments: true
exclude:
  - README.md
